# Generated by Django 4.2.5 on 2023-09-16 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_coursegroup_row'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursegroup',
            name='required',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
