# Generated by Django 4.2.5 on 2023-10-17 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_courseselection'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coursebase',
            old_name='index',
            new_name='column',
        ),
        migrations.AlterField(
            model_name='courseselection',
            name='semester',
            field=models.CharField(choices=[('FL', 'Fall'), ('SP', 'Spring'), ('S1', 'Summer 1'), ('S2', 'Summer 2'), ('CR', 'Credit')], max_length=2),
        ),
    ]
