# Generated by Django 4.2.5 on 2023-10-17 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rename_index_coursebase_column_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursegroup',
            name='hidden',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
